name: 'Hatchbox Deploy Action'
description: 'Send deployment notifications to the Hatchbox API'
branding:
  icon: 'globe'
  color: 'red'
inputs:
  deploy_key:
    description: 'The Hatchbox project deploy key'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:

    - ${{ inputs.deploy_key }}
